#!/bin/bash

ffmacos_dependency_matrix() {
    cat <<'EOF'
FF_ENABLE_X264|x264|x264|
FF_ENABLE_X265|x265|x265|
FF_ENABLE_LIBAOM|aom|aom|
FF_ENABLE_LIBVPX|libvpx|vpx|
FF_ENABLE_LIBOPUS|libopus|opus|
FF_ENABLE_LIBWEBP|libwebp|libwebp|
FF_ENABLE_LIBVORBIS|libvorbis|vorbis|
FF_ENABLE_LIBASS|libass|libass|
FF_ENABLE_LIBBLURAY|libbluray|libbluray|
FF_ENABLE_LIBOPENJPEG|openjpeg|libopenjp2|
FF_ENABLE_LIBSRT|srt|srt|
FF_ENABLE_LIBSOXR|soxr|soxr|soxr
FF_ENABLE_LIBZIMG|zimg|zimg|
FF_ENABLE_LIBSSH|libssh|libssh|
FF_ENABLE_LIBZMQ|libzmq|libzmq|
FF_ENABLE_LIBSNAPPY|snappy|snappy|snappy
FF_ENABLE_LIBOPENMPT|openmpt|libopenmpt|
FF_ENABLE_LIBSAMPLERATE|libsamplerate|samplerate|
FF_ENABLE_LIBKVAZAAR|kvazaar|kvazaar|
FF_ENABLE_SDL2|sdl|sdl2|
FF_ENABLE_LIBGME|gme|libgme|
FF_ENABLE_LIBARIBCAPTION|libaribcaption|libaribcaption|
FF_ENABLE_LIBRUBBERBAND|rubberband|rubberband|
FF_ENABLE_LIBVVENC|vvenc|libvvenc|
FF_ENABLE_WHISPER|whisper|whisper|
FF_ENABLE_LIBXVID|xvid|xvid|xvid
FF_ENABLE_LIBDAVS2|davs2|davs2|
FF_ENABLE_LIBFDK_AAC|fdk-aac|fdk-aac|
FF_ENABLE_FFNVCODEC|ffnvcodec|ffnvcodec|
FF_ENABLE_LIBLCEVCDEC|lcevcdec|liblcevc_dec|
FF_ENABLE_AMF|amf|amf|
FF_ENABLE_LIBVPL|onevpl|libvpl|
FF_ENABLE_SCHANNEL|schannel||
FF_ENABLE_LIBUAVS3D|uavs3d|uavs3d|
FF_ENABLE_LIBXAVS2|xavs2|xavs2|
FF_ENABLE_LIBZVBI|zvbi|zvbi-0.2|
FF_ENABLE_LIBDAV1D|dav1d|dav1d|
FF_ENABLE_LIBTHEORA|libtheora|theoraenc|theora
FF_ENABLE_LIBTWOLAME|twolame|twolame|twolame
FF_ENABLE_LIBOPENH264|openh264|openh264|
FF_ENABLE_LIBRAV1E|rav1e|rav1e|
FF_ENABLE_LIBMP3LAME|libmp3lame|lame|mp3lame
FF_ENABLE_CHROMAPRINT|chromaprint|libchromaprint|
FF_ENABLE_LIBOPENCORE_AMR|opencore-amr|opencore-amrnb|opencore_amr
FF_ENABLE_OPENAL|openal|openal|
FF_ENABLE_LIBSVTAV1|svtav1|SvtAv1Enc|
FF_ENABLE_GMP|gmp|gmp|gmp
FF_ENABLE_LIBFRIBIDI|fribidi|fribidi|
FF_ENABLE_FREI0R|frei0r|frei0r|frei0r
FF_ENABLE_LIBVIDSTAB|vidstab|vidstab|
FF_ENABLE_LIBVMAF|vmaf|libvmaf|
EOF
}
